# Generated by Django 3.2.8 on 2022-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220323_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='account',
            name='history',
            field=models.ManyToManyField(related_name='history', to='blog.Post'),
        ),
    ]
