# Generated by Django 3.2.8 on 2022-04-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_category_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='word',
        ),
    ]
