# Generated by Django 3.2.8 on 2022-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_name_category_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='categories_disliked',
            field=models.ManyToManyField(related_name='categories_disliked', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='account',
            name='categories_liked',
            field=models.ManyToManyField(related_name='categories_liked', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='probability',
            field=models.FloatField(default=0),
        ),
    ]
