# Generated by Django 3.2.8 on 2022-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220417_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reputation',
            field=models.FloatField(default=0),
        ),
    ]
