# Generated by Django 3.2.8 on 2022-04-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reputation',
        ),
        migrations.AddField(
            model_name='account',
            name='reputation',
            field=models.FloatField(default=0),
        ),
    ]
