# Generated by Django 3.2.8 on 2022-04-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220423_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='history',
            field=models.ManyToManyField(related_name='history', to='blog.Post'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
